[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "alfese"
version = "1.1.0"
authors = [
    {name="Jakob Bach", email="jakob.bach.ka@gmail.com"},
]
description = "Alternative feature selection"
keywords = ["feature selection", "alternatives", "constraints"]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.22.3",
    "ortools>=9.3.10497",
    "pandas>=1.4.1",
    "scikit-learn>=1.0.2",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Jakob-Bach/Alternative-Feature-Selection/tree/main/alfese_package"
Issues = "https://github.com/Jakob-Bach/Alternative-Feature-Selection/issues"

[tool.ruff]
line-length = 100
target-version = "py38"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812", # missing trailing comma
    "D", # documentation linting
    "EM101", # passing string literal to Exception initializer (instead of assigning to variable first)
    "N803", # argument name not in snake case (may refer to upper-case variables from problem formulation like Q or X)
    "N806", # variable name not in snake case (may refer to upper-case variables from problem formulation like Q or X)
    "Q000", # due to historic reasons, we use single quotes as primary quotes in code
    "S101", # asserts
    "TRY003", # passing message to Exception initializer instead of specifying separate class
    "UP007", # old "Union" type annotation (without |)
    "UP045", # old "Optional" type annotation (without |)
]
